// Доменная модель Marketing Club. См. docs/ARCHITECTURE.md §3–4 и docs/PUBLISHING_CONTRACT.md.
// Только снятие типов (нативный TS в Node 24): без enum, объединения строковых литералов.

                    
                                                                                      
                                                                              
                                                                   

// Порядок ролей для отображения и профилей проектов (по командам, как в docs/AGENT_CATALOG.md).
export const ROLE_ORDER           = ['marketing-director', 'brand-strategist', 'market-researcher', 'seo-strategist', 'chief-editor', 'creative-director', 'reels-producer', 'channel-editor', 'quality-controller', 'funnel-analyst', 'publisher-executor'];

                                                                                  
                                                                                                        
                                                                       
                                                                                                                          
                                                                                                                      
                                                                                         
                                                                         
                                                                                                  
                                                                                                    
                                                                             
                                                                                   
                                                         
                                                                                                                           
                                                 
                          
                                                                                                 
                                                                                           

                   
                                   
                                     
                       

                                                                            

                                                                                                                   
                                                                                         
                                                                                               

                            
                    
                  
                     
                  
                      
  

                             
             
                     
                          
                          
                         
                 
                    
                                                                                                 
  

                               
             
               
               
                 
                  
                                                         
                                                                                            
                      
                         
                                                                                                                                              
                                                     
                                            
                
                 
  

                             
             
                    
                 
                        
                 
                      
                               
                           
                           
               
                        
  

                                                                                      

                              
             
                    
                     
               
                           
                   
                     
                                             
  

                       
             
               
                  
                   
                    
                        
                   
                                                                                                                  
                                                                                    
                      
                                                                                                                
                         
                      
  

                            
             
                 
               
                                
                        
                  
                
                    
                        
                  
                               
                                
                                
                            
                  
                        
                    
  

                    
             
                    
                
                 
               
                     
                  
                                                       
                           
                        
                  
                               
                        
                    
                    
                    
                                   
                            
                                                                         
                     
                                                                  
                                                                   
  

                               
                  
                
               
              
                     
                      
                  
                 
  

                               
             
                    
                 
                     
                  
                
               
              
                     
                 
                           
                             
                   
                    
                
                         
                      
                            
                       
                                      
                            
                                                           
                              
                         
                    
                    
  

                        
             
                    
                     
                          
                      
                    
                      
                   
                     
                     
                               
                               
                           
  

// Личная отметка согласующего «решить позже». Это порядок просмотра, а не решение
// по материалу: она не входит в contentHash и не меняет статус/Approval.
                              
                    
                     
                          
                     
                     
  

                              
                     
                  
                      
                
               
              
                     
                 
                     
                      
                   
                                                                                  
                                                                                
                   
  

                             
                                                         
                                                                     

                          
             
                    
                     
                     
                    
                           
                    
                  
                          
                                                          
                      
                                 
                    
                    
                            
  

                                  
                  
               
                        
               
                                                                                                  
  

                             
             
                    
             
               
                  
               
                  
                                                                                                                           
  

                        
             
                    
               
               
                   
                    
                                                     
                       
                                                            
                                            
                                                                                                               
                    
  

                                 
             
               
                                                             
                                             
                                                                                                      
                                                
                                                     
  

                            
                   
                
                          
                             
                
                               
                        
                                    
                     
                        
                          
                               
                                   
                                                                                            
                                                                    
                              
                                                                                       
                                                                                        
                          
  

                          
                     
                   
                     
                                                    
                
                   
                                                
                                          
                  
                     
                      
                                                                                             
                    
                    
  

                             
             
              
                
                  
                    
                   
                                                                     
                                                                                            
  

export class DomainError extends Error {
  code        ;
  constructor(code        , message        ) {
    super(message);
    this.code = code;
  }
}
